# Generated by Django 5.0 on 2024-01-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_alter_student_age_alter_student_father_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
