# Generated by Django 5.0 on 2024-01-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
